
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.Embeds
{
    using System;
using UnityEngine.Networking;
using Newtonsoft.Json;
using SDK.Utils;
    using System.Collections.Generic;
    public class RevokeEmbedAccessTokenRequest
    {
    /// <summary>
    /// The ID of the EmbedToken to revoke.
    /// </summary>
        
        [JsonProperty("tokenID")]
        public string TokenID { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, RevokeEmbedAccessTokenRequest value, string baseUrl)
        {
            if("revokeEmbedAccessToken" == operationId)
            {
                
                var tokenID = PathParamSerializer.Serialize("simple", false, value.TokenID);var urlString = baseUrl + $"/v1/workspace/embed-access-tokens/{tokenID}";// #request-debugging Delete 
                var message = UnityWebRequest.Delete(urlString);
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [RevokeEmbedAccessTokenRequest]");
        }
    }

}