
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.Schemas
{
    using System;
using UnityEngine.Networking;
using Newtonsoft.Json;
using SDK.Utils;
    using System.Collections.Generic;
    public class RegisterSchemaRequest
    {
    /// <summary>
    /// The schema file to upload provided as a multipart/form-data file segment.
    /// </summary>
        
        [JsonProperty("RequestBody")]
        public RegisterSchemaRequestBody RequestBody { get; set; }
        
    /// <summary>
    /// The ID of the Api to get the schema for.
    /// </summary>
        
        [JsonProperty("apiID")]
        public string ApiID { get; set; }
        
    /// <summary>
    /// The version ID of the Api to delete metadata for.
    /// </summary>
        
        [JsonProperty("versionID")]
        public string VersionID { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, RegisterSchemaRequest value, string baseUrl)
        {
            if("registerSchema" == operationId)
            {
                
                
                var apiID = PathParamSerializer.Serialize("simple", false, value.ApiID);
                
                var versionID = PathParamSerializer.Serialize("simple", false, value.VersionID);
                // #request-debugging post with a file
                // TODO: code review
                
                var name = Utilities.ToString(value.RequestBody.File.Content);
                var bytes = value.RequestBody.File.Content;
                var filename = value.RequestBody.File.File;
                List<IMultipartFormSection> formData = new List<IMultipartFormSection>();
                formData.Add(new MultipartFormFileSection(name, bytes, filename, "application/octet-stream"));var urlString = baseUrl + $"/v1/apis/{apiID}/version/{versionID}/schema";// #request-debugging post TODO: work in progress
                UnityWebRequest message;
                message = UnityWebRequest.Post(urlString, formData);
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [RegisterSchemaRequest]");
        }
    }

}