
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.Requests
{
    using System;
using UnityEngine.Networking;
using Newtonsoft.Json;
using SDK.Utils;
    using System.Collections.Generic;
    public class GenerateRequestPostmanCollectionRequest
    {
    /// <summary>
    /// The ID of the request to retrieve.
    /// </summary>
        
        [JsonProperty("requestID")]
        public string RequestID { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, GenerateRequestPostmanCollectionRequest value, string baseUrl)
        {
            if("generateRequestPostmanCollection" == operationId)
            {
                
                var requestID = PathParamSerializer.Serialize("simple", false, value.RequestID);var urlString = baseUrl + $"/v1/eventlog/{requestID}/generate/postman";// #request-debugging Get 
                var message = UnityWebRequest.Get(urlString);
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [GenerateRequestPostmanCollectionRequest]");
        }
    }

}