
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.Requests
{
    using System;
using System.Collections.Generic;
using UnityEngine.Networking;
using Newtonsoft.Json;
using SDK.Models.Shared;
using SDK.Utils;
    using System.Collections.Generic;
    public class QueryEventLogRequest
    {
    /// <summary>
    /// The filter to apply to the query.
    /// </summary>
        
        [JsonProperty("filters")]
        public Filters? Filters { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, QueryEventLogRequest value, string baseUrl)
        {
            if("queryEventLog" == operationId)
            {
                var queryParams = new List<string>();
                
                queryParams.Add($"filters={JsonConvert.SerializeObject(value.Filters, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, Converters = new JsonConverter[] { new IsoDateTimeSerializer(), new EnumSerializer() }})}");
                var queryParamString = $"?{String.Join("&", queryParams)}";var urlString = baseUrl + "/v1/eventlog/query" + queryParamString;// #request-debugging Get 
                var message = UnityWebRequest.Get(urlString);
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [QueryEventLogRequest]");
        }
    }

}