
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.Metadata
{
    using System;
using UnityEngine.Networking;
using System.Text;
using Newtonsoft.Json;
using SDK.Models.Shared;
using SDK.Utils;
    using System.Collections.Generic;
    public class InsertVersionMetadataRequest
    {
    /// <summary>
    /// A JSON representation of the metadata to insert.
    /// </summary>
        
        [JsonProperty("VersionMetadataInput")]
        public VersionMetadataInput VersionMetadataInput { get; set; }
        
    /// <summary>
    /// The ID of the Api to insert metadata for.
    /// </summary>
        
        [JsonProperty("apiID")]
        public string ApiID { get; set; }
        
    /// <summary>
    /// The version ID of the Api to insert metadata for.
    /// </summary>
        
        [JsonProperty("versionID")]
        public string VersionID { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, InsertVersionMetadataRequest value, string baseUrl)
        {
            if("insertVersionMetadata" == operationId)
            {
                
                
                var apiID = PathParamSerializer.Serialize("simple", false, value.ApiID);
                
                var versionID = PathParamSerializer.Serialize("simple", false, value.VersionID);
                string json = JsonConvert.SerializeObject(value.VersionMetadataInput, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, Converters = new JsonConverter[] { new IsoDateTimeSerializer(), new EnumSerializer() }});var urlString = baseUrl + $"/v1/apis/{apiID}/version/{versionID}/metadata";// #request-debugging post TODO: work in progress
                UnityWebRequest message;message = UnityWebRequest.Post(urlString, json, "application/json");
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [InsertVersionMetadataRequest]");
        }
    }

}