
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SDK.Models.Shared
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
/// <summary>
/// The `Status` type defines a logical error model
/// </summary>
    public class Error
    {
    /// <summary>
    /// A developer-facing error message.
    /// </summary>
        
        [JsonProperty("message")]
        public string Message { get; set; }
        
    /// <summary>
    /// The HTTP status code
    /// </summary>
        
        [JsonProperty("status_code")]
        public int StatusCode { get; set; }
        
    }

}